name: Docker Builder - Node 16

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/node-16.yml
      - docker/docker-entrypoint.sh
  pull_request:
    paths:
      - .github/workflows/node-16.yml
      - docker/docker-entrypoint.sh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: gperdomor/nx-tools/.github/workflows/.node-template.yml@1fb4eb34d401fda7ee59f2283bed56978207e5ac
        with:
          node-version: 16.10.0
        secrets:
          token: ${{ secrets.GITHUB_TOKEN }}
